services:
    backend:
        build:
            context: ./backend
            dockerfile: Dockerfile
        container_name: backend
        restart: always
        ports:
            - "3000:3000"

    frontend:
        build:
            context: ./frontend
            dockerfile: Dockerfile
        container_name: frontend
        depends_on:
            - backend
        restart: always
        ports:
            - "5050:3000"
